In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\Diksha\Downloads\cust_satisfaction.csv")

In [4]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [5]:
df.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df["Customer Type"] = df["Customer Type"].str.strip().str.lower()
df["Type of Travel"] = df["Type of Travel"].str.strip().str.lower()
df["Gender"] = df["Gender"].str.strip().str.lower()
df["Class"] = df["Class"].str.strip().str.lower()
df["satisfaction"] = df["satisfaction"].str.strip().str.lower()

In [8]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

Index(['gender', 'customer_type', 'type_of_travel', 'class', 'satisfaction',
       'age', 'flight_distance', 'inflight_entertainment', 'baggage_handling',
       'cleanliness', 'departure_delay_in_minutes',
       'arrival_delay_in_minutes'],
      dtype='object')

In [9]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [10]:
df["gender"] = df["gender"].map({"male": 0, "female": 1})
df["satisfaction"] = df["satisfaction"].map({
    "neutral or dissatisfied": 0,
    "satisfied": 1
})

In [11]:
df = pd.get_dummies(df, columns=["class", "type_of_travel"], drop_first=True)

In [12]:
df.query("age > 20 and flight_distance > 200")

,gender,customer_type,satisfaction,age,flight_distance,inflight_entertainment,baggage_handling,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,class_eco,class_eco plus,type_of_travel_personal travel
1,0,disloyal customer,0,25,235,1,3,1,1,6.0,False,False,False
2,1,loyal customer,1,26,1142,5,4,5,0,0.0,False,False,False
3,1,loyal customer,0,25,562,2,3,2,11,9.0,False,False,False
4,0,loyal customer,1,61,214,3,4,3,0,0.0,False,False,False
5,1,loyal customer,0,26,1180,1,4,1,0,0.0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103898,0,loyal customer,0,50,1620,2,4,2,0,0.0,True,False,True
103900,0,loyal customer,1,49,2347,5,5,4,0,0.0,False,False,False
103901,0,disloyal customer,0,30,1995,4,4,4,7,14.0,False,False,False
103902,1,disloyal customer,0,22,1000,1,1,1,0,0.0,True,False,False
103903,0,loyal customer,0,27,1723,1,4,1,0,0.0,False,False,False

In [13]:
df.sort_values(by="flight_distance", ascending=False)

,gender,customer_type,satisfaction,age,flight_distance,inflight_entertainment,baggage_handling,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,class_eco,class_eco plus,type_of_travel_personal travel
64791,1,loyal customer,1,50,4983,2,4,4,0,0.0,False,False,False
95982,1,loyal customer,0,62,4983,2,4,4,0,0.0,False,True,True
33094,1,loyal customer,0,29,4983,2,4,4,6,0.0,True,False,True
46848,0,loyal customer,1,42,4983,4,3,4,0,0.0,False,False,False
67767,0,loyal customer,1,67,4983,1,5,1,0,0.0,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69088,1,loyal customer,0,12,31,1,2,1,12,8.0,True,False,True
88552,0,loyal customer,1,43,31,4,5,4,0,0.0,False,True,False
15925,1,disloyal customer,1,23,31,1,4,1,0,0.0,True,False,False
24808,1,loyal customer,0,54,31,5,5,2,18,22.0,True,False,True
87950,1,loyal customer,0,17,31,1,5,1,11,11.0,True,False,True

In [14]:
df.groupby("satisfaction")["age"].mean()

satisfaction
0    37.570230
1    41.742643
Name: age, dtype: float64

In [15]:
df["gender"].value_counts()

gender
1    52500
0    50922
Name: count, dtype: int64

In [16]:
df["total_delay"] = df["departure_delay_in_minutes"] + df["arrival_delay_in_minutes"]
df.head()

,gender,customer_type,satisfaction,age,flight_distance,inflight_entertainment,baggage_handling,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,class_eco,class_eco plus,type_of_travel_personal travel,total_delay
0,0,loyal customer,0,13,460,5,4,5,25,18.0,False,True,True,43.0
1,0,disloyal customer,0,25,235,1,3,1,1,6.0,False,False,False,7.0
2,1,loyal customer,1,26,1142,5,4,5,0,0.0,False,False,False,0.0
3,1,loyal customer,0,25,562,2,3,2,11,9.0,False,False,False,20.0
4,0,loyal customer,1,61,214,3,4,3,0,0.0,False,False,False,0.0

In [17]:
Q1 = df["flight_distance"].quantile(0.25)
Q3 = df["flight_distance"].quantile(0.75)
IQR = Q3 - Q1

df = df[(df["flight_distance"] >= Q1 - 1.5*IQR) &
        (df["flight_distance"] <= Q3 + 1.5*IQR)]

In [18]:
df.corr(numeric_only=True)

,gender,satisfaction,age,flight_distance,inflight_entertainment,baggage_handling,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,class_eco,class_eco plus,type_of_travel_personal travel,total_delay
gender,1.000000,-0.012576,-0.009023,-0.006776,-0.006433,-0.038348,-0.006170,-0.002853,-0.000765,0.005167,0.010594,-0.006904,-0.001816
satisfaction,-0.012576,1.000000,0.134235,0.286351,0.392531,0.242286,0.301021,-0.050263,-0.057076,-0.446457,-0.102582,-0.446246,-0.054167
age,-0.009023,0.134235,1.000000,0.092494,0.074800,-0.049734,0.053212,-0.009654,-0.011472,-0.129012,-0.011786,-0.044949,-0.010663
flight_distance,-0.006776,0.286351,0.092494,1.000000,0.120851,0.060348,0.089790,0.000970,-0.002934,-0.389211,-0.118474,-0.252434,-0.001006
inflight_entertainment,-0.006433,0.392531,0.074800,0.120851,1.000000,0.370693,0.696597,-0.026972,-0.029807,-0.172406,-0.043353,-0.144775,-0.028650
baggage_handling,-0.038348,0.242286,-0.049734,0.060348,0.370693,1.000000,0.092206,-0.004490,-0.007263,-0.138362,-0.062811,-0.029505,-0.005939
cleanliness,-0.006170,0.301021,0.053212,0.089790,0.696597,0.092206,1.000000,-0.013387,-0.015259,-0.120633,-0.032135,-0.076608,-0.014456
departure_delay_in_minutes,-0.002853,-0.050263,-0.009654,0.000970,-0.026972,-0.004490,-0.013387,1.000000,0.965362,0.008675,0.004206,-0.005993,0.991164
arrival_delay_in_minutes,-0.000765,-0.057076,-0.011472,-0.002934,-0.029807,-0.007263,-0.015259,0.965362,1.000000,0.011825,0.006391,-0.005823,0.991440
class_eco,0.005167,-0.446457,-0.129012,-0.389211,-0.172406,-0.138362,-0.120633,0.008675,0.011825,1.000000,-0.260191,0.494218,0.010352
class_eco plus,0.010594,-0.102582,-0.011786,-0.118474,-0.043353,-0.062811,-0.032135,0.004206,0.006391,-0.260191,1.000000,0.099247,0.005354
type_of_travel_personal travel,-0.006904,-0.446246,-0.044949,-0.252434,-0.144775,-0.029505,-0.076608,-0.005993,-0.005823,0.494218,0.099247,1.000000,-0.005959
total_delay,-0.001816,-0.054167,-0.010663,-0.001006,-0.028650,-0.005939,-0.014456,0.991164,0.991440,0.010352,0.005354,-0.005959,1.000000

In [ ]:
df.to_csv("cleaned_airline_data.csv", index=False)